data = [
    # Georgia
    ['Kakheti', 10.2], 
    ['Imereti', 10.7], 
    ['Kvemo Kartli', 11.1], 
    ['Samegrelo-Zemo Svaneti', 8.9], 
    ['Samtskhe-Javakheti', 11], 
    ['Tbilisi', 11], 
    ['Abkhazia', 5], 
    ['Mtskheta-Mtianeti', 9.1], 
    ['Shida Kartli', 10.1], 
    ['Guria', 8.6], 
    ['Racha-Lechkhumi-Kvemo Svaneti', 8.5], 
    ['Ajaria', 13.9], 
    # Russia
    ['Dagestan', 13.4], 
    ['Chechnya', 19.7], 
    ['North Ossetia', 10.6], 
    ['Ingush', 15],
    ['Kabardin-Balkar', 11], 
    ['Karachay-Cherkess', 9.4], 
    ['Adygey', 9.5], 
    ['Stavropolskiy Kray', 9.1], 
    ['Krasnodarskiy Kray', 9.5],
    # Azerbaijan   
    ['Bakı', 9.7],
    ['Shirvan', 14],
    ['Gəncə', 10.1],
    ['Mingəçevir', 12.3],
    ['Qazax', 12],
    ['Naxçıvan', 9.2],
    ['Abşeron', 6.6],
    ['Quba', 12.3],
    ['Salyan', 12.5],
    ['Lankaran', 13.1],
    ['Stepanakert', 13.2],
    ['Ağcabədi', 13.2],
    # Armenia
    ['Yerevan', 9.9],
    ['Aragatsotn', 15.4],
    ['Ararat', 15.2],       
    ['Armavir', 14.0],
    ['Gegharkunik', 12.7],
    ['Lori', 13.0],
    ['Kotayk', 14.5],
    ['Shirak', 12.2],
    ['Syunik', 12.6],
    ['Vayots Dzor', 14.5],
    ['Tavush', 12.3],
]